### ISSUE TITLE
Tenancy selection prompt keeps on appearing even if disabled

### ISSUE THREAD

**Issue by honiewelle** [opendistro-for-elasticsearch/security-kibana-plugin#2]
Hi. We're currently using the version `1.13.2` and have disabled the tenancy using the following configuration (below) but we're still seeing the prompt as can be seen in the screenshot:

`/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml`
```
...
config:
  dynamic:
    do_not_fail_on_forbidden: true
    kibana:
      multitenancy_enabled: false
    http:
...
```

`/etc/kibana.yml`
```
opendistro_security.multitenancy.enabled: false
opendistro_security.multitenancy.tenants.enable_private: false
opendistro_security.multitenancy.tenants.enable_global: false
opendistro_security.multitenancy.tenants.preferred: ["Global"]
opendistro_security.multitenancy.enable_filter: false
```

<img width="785" alt="image" src="https://user-images.githubusercontent.com/758187/116974245-69145200-acf0-11eb-81c4-9a61cf1afd16.png">
