### ISSUE TITLE
Unable to retrieve version information from Elasticsearch nodes.

### ISSUE THREAD

**Issue by BlackMetalz** [opendistro-for-elasticsearch/security-kibana-plugin#250]
My docker-compose for kibana:
```
version: '3'
services:
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.7.0
    container_name: odfe-kibana-standalone
    ports:
      - 5601:5601
    expose:
      - "5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
```

kibana.yml
```
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: "http://10.3.48.54:9200"
```

curl 10.3.48.54:9200 with auth and insecure output:
```
{
  "name" : "10.3.48.54",
  "cluster_name" : "odfe-cluster",
  "cluster_uuid" : "V6Y68UwbQRGNuU1xw9Z79Q",
  "version" : {
    "number" : "7.6.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "aa751e09be0a5072e8570670309b1f12348f023b",
    "build_date" : "2020-02-29T00:15:25.529771Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
I'm using version 1.7.0 for both odfe and kibana. But I have installed a custom plugin for odfe. Not sure it can caused this error or not. 

Thanks for reading and hope i can receive reply soon
