### ISSUE TITLE
Automate Index Pattern Creation Per Tenant?

### ISSUE THREAD

**Issue by DerekHeldtWerle** [opendistro-for-elasticsearch/security-kibana-plugin#30]
We work in a multi-tenant environment, and I was hoping to automate the creation of index patterns on a per-tenant basis. 

We have roles similar to the following:
```
team_users:
  indices:
    'namespace-team-*':
      '*':
        - READ
  tenants:
    team_tenant: RO

admin_team_users:
  indices:
    'namespace-team-*':
      '*':
        - UNLIMITED
  tenants:
    team_tenant: RW
.
.
.
```
And roles_mappings:
```
team_users:
  backendroles:
    - k8s-team-admins
    - k8s-team-users

admin_team_users:
  backendroles:
    - k8s-admins
.
.
.
```

The above successfully allows members of the k8s-admins group to log into kibana, switch to the matching `team_tenant`, and create index patterns (currently of the form `namespace-team-*`). With this, the members of the `k8s-team-admins/users` groups now have read-only access to the logs in their given namespace. 

Ideally, we would like to be able to issue a curl command from our local machines as admin users, using a specific `team_tenant` that we have `RW` access to, and set up the index pattern of the form `namespace-team-*`. As of yet, I haven't been able to track down if this is supported, but may be missing something. Any help would be greatly appreciated!
