### ISSUE TITLE
SAML integration fails

### ISSUE THREAD

**Issue by juliennix** [opendistro-for-elasticsearch/security-kibana-plugin#599]
Hello,
When integrating ES and kibana with SAML, we faced this error:

in the folloing: security-kibana-plugin\server\backend\opendistro_security_client.ts
We got: failed parsing SAML config
And I spotted that the expected error do not have the information:
Authentication Exception :: {"path":"/_opendistro/_security/authinfo","query":{},"statusCode":401,"response":"Unauthorized","wwwAuthenticateDirective":"Basic realm=\"Open Distro Security\""}

here is our config:

ES security:
```_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        #remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      saml_auth_domain:
        http_enabled: true
        description: "SAML provider"
        transport_enabled: true
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: "{{ elk_metada_url }}"
              entity_id: "{{ elk_entity_id }}"
            sp:
              entity_id: "{{ kibana_cname_host }}"
              acs: "{{ kibana_cname_host }}/_opendistro/_security/saml/acs"
            kibana_url: "{{ kibana_cname_host }}"
            exchange_key: "{{ elk_exchange_key }}"
        authentication_backend:
          type: noop
      ldap:
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - dc.shared.enocloud.eu:389
            bind_dn: {{ bind_dn }}
            password:  {{ password}}
            userbase:  {{ userbase}}
            usersearch: '(sAMAccountName={0})'
            username_attribute: sAMAccountName
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/root-ca.pem

      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

and Kibana: 
```
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.allow_client_certificates: true
opendistro_security.auth.type: "saml"
newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false
server.host: "0.0.0.0"
server.name: kibana
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
elasticsearch.hosts: ["https://odfe-node1:9200"]
elasticsearch.username: "{{ kibana_open_distro_user }}"
elasticsearch.password: "{{ kibana_open_distro_password }}"
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/kibana.crt
server.ssl.key: /usr/share/kibana/config/kibana.key
elasticsearch.ssl.certificate: /usr/share/elasticsearch/config/client.crt
elasticsearch.ssl.key: /usr/share/elasticsearch/config/client.key
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/root-ca.pem"]
elasticsearch.ssl.verificationMode: certificate
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]



{% if opendistro_docker_version == '1.10.1' -%}
opendistro_security.cookie.secure: false
{%- endif %}
```

Why is that ? What could be the issue, the metadata.xml ?

**Comment by zengyan-amazon** [comment]
@juliennix this looks like a configuration issue, I see in your ES security plugin config, you have enabled both basic auth and SAML

```
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

```
      saml_auth_domain:
        http_enabled: true
        description: "SAML provider"
        transport_enabled: true
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: "{{ elk_metada_url }}"
              entity_id: "{{ elk_entity_id }}"
            sp:
              entity_id: "{{ kibana_cname_host }}"
              acs: "{{ kibana_cname_host }}/_opendistro/_security/saml/acs"
            kibana_url: "{{ kibana_cname_host }}"
            exchange_key: "{{ elk_exchange_key }}"
        authentication_backend:
          type: noop
```

While the problem here is that both of them has `http. challenge ` set to `true`, and basic auth has the order of `0` which while saml has order of `1`. Thus when a request failed basic authentication, ES security plugin will return the challenge response, then you see the error message `{"path":"/_opendistro/_security/authinfo","query":{},"statusCode":401,"response":"Unauthorized","wwwAuthenticateDirective":"Basic realm="Open Distro Security""}`

You may try to set basic auth http challenge to `false`, that should fix the issue
